"theme:workflow":
  - changed-files:
      - any-glob-to-any-file: ".github/**"

"theme:build":
  - changed-files:
      - any-glob-to-any-file:
          - ".editorconfig"
          - ".eslintrc.js"
          - ".gitignore"
          - ".prettierrc"
          - "lerna.json"
          - "package.json"
          - "tsconfig.json"
          - ".husky/**"

"theme:codeceptjs":
  - changed-files:
      - any-glob-to-any-file: "packages/allure-codeceptjs/**"

"theme:cucumberjs":
  - changed-files:
      - any-glob-to-any-file: "packages/allure-cucumberjs/**"

"theme:decorators":
  - changed-files:
      - any-glob-to-any-file: "packages/allure-decorators/**"

"theme:jasmine":
  - changed-files:
      - any-glob-to-any-file: "packages/allure-jasmine/**"

"theme:jest":
  - changed-files:
      - any-glob-to-any-file: "packages/allure-jest/**"

"theme:api":
  - changed-files:
      - any-glob-to-any-file: "packages/allure-js-commons/**"

"theme:mocha":
  - changed-files:
      - any-glob-to-any-file: "packages/allure-mocha/**"

"theme:playwright":
  - changed-files:
      - any-glob-to-any-file: "packages/allure-playwright/**"

"theme:testcafe":
  - changed-files:
      - any-glob-to-any-file: "packages/testcafe-reporter-allure-official/**"

"theme:vitest":
  - changed-files:
      - any-glob-to-any-file: "packages/allure-vitest/**"

"theme:newman":
  - changed-files:
      - any-glob-to-any-file: "packages/newman-reporter-allure/**"
