---
root: true

parser: "@typescript-eslint/parser"

parserOptions:
    sourceType: module

plugins:
    - typescript

extends:
    - eslint:recommended

globals:
    allure: true

env:
    es6: true
    node: true
    jasmine: true

rules:
    no-console: off
    no-undef: off
    no-unused-vars: off
    valid-jsdoc: off
    no-multi-spaces: error
    no-return-await: error
    require-await: warn
    no-self-compare: error
    no-useless-concat: error
    arrow-body-style: [error, as-needed]
    arrow-parens: [error, as-needed]
    arrow-spacing: error
    no-confusing-arrow: error
    no-var: error
    object-shorthand: [error, consistent-as-needed]
    prefer-const: error
    prefer-destructuring: warn
    prefer-rest-params: warn
    prefer-spread: warn
    prefer-template: error
    array-bracket-spacing: [error, never]
    block-spacing: [error, always]
    brace-style:
        - error
        - 1tbs
        -
            allowSingleLine: true
    camelcase: warn
    comma-spacing: error
    comma-style: error
    func-call-spacing: error
    func-style:
        - error
        - declaration
        -
            allowArrowFunctions: true
    indent:
        - error
        - "tab"
        -
            SwitchCase: 1
    key-spacing: error
    keyword-spacing: warn
    max-len: [warn, 140]
    new-cap: warn
    new-parens: error
    no-multiple-empty-lines: error
    no-nested-ternary: error
    no-trailing-spaces: error
    no-whitespace-before-property: error
    nonblock-statement-body-position: error
    object-curly-newline:
        - error
        -
            consistent: true
    object-curly-spacing: [warn, always]
    object-property-newline:
        - error
        -
            allowMultiplePropertiesPerLine: true
    padded-blocks: [error, never]
    quotes: [error, double]
    semi: error
    semi-spacing: error
    semi-style: error
    space-before-blocks: error
    space-before-function-paren: [error, never]
    space-in-parens: error
    space-infix-ops: error
