compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  codeceptjs@*:
    dependencies:
      debug: "*"
  newman@*:
    peerDependencies:
      newman-reporter-allure: "workspace:*"
  detox@*:
    dependencies:
      react-native: "*"

plugins:
  - ./plugin-ci-version.cjs

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.6.0.cjs
