compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  codeceptjs@*:
    dependencies:
      debug: "*"
  allure-js-commons@*:
    dependencies:
      allure-playwright: "workspace:*"
      allure-vitest: "workspace:*"

plugins:
  - ./plugin-ci-version.js

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.2.2.cjs
