enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  codeceptjs@*:
    dependencies:
      debug: "*"
  detox@*:
    dependencies:
      react-native: "*"
  newman@*:
    peerDependencies:
      newman-reporter-allure: "workspace:*"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.9.1.cjs
