compressionLevel: mixed

enableGlobalCache: false

plugins:
  - ./plugin-ci-version.js

packageExtensions:
  codeceptjs@*:
    dependencies:
      debug: "*"
  hermione@*:
    dependencies:
      escape-string-regexp: 1.0.5
  newman@*:
    dependencies:
      liquid-json: "*"
      newman-reporter-allure: "*"
  postman-sandbox@*:
    dependencies:
      postman-collection: "*"

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.1.1.cjs
