packageExtensions:
  codeceptjs@*:
    dependencies:
      debug: "*"
  hermione@*:
    dependencies:
      escape-string-regexp: 1.0.5
  postman-sandbox@*:
    dependencies:
      postman-collection: "*"
  newman@*:
    dependencies:
      newman-reporter-allure: "*"
      liquid-json: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl

yarnPath: .yarn/releases/yarn-4.1.1.cjs
