compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  codeceptjs@*:
    dependencies:
      debug: "*"
  newman@*:
    dependencies:
      newman-reporter-allure: "workspace:*"
  allure-js-commons@*:
    dependencies:
      allure-playwright: "workspace:*"
      allure-vitest: "workspace:*"

plugins:
  - ./plugin-ci-version.cjs

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.3.1.cjs
