compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  codeceptjs@*:
    dependencies:
      debug: "*"
  hermione@*:
    dependencies:
      escape-string-regexp: 1.0.5
  newman@*:
    dependencies:
      liquid-json: "*"
      newman-reporter-allure: "*"
  postman-sandbox@*:
    dependencies:
      postman-collection: "*"

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl

plugins:
  - ./plugin-ci-version.js

yarnPath: .yarn/releases/yarn-4.0.2.cjs
